sudo: false
language: c
os:
  # osx starts faster because homebrew installs beat building from source
  - osx
  - linux
compiler:
  - clang
  - gcc
matrix:
  allow_failures:
    - env: MPI_IMPL=openmpi
env:
  - MPI_IMPL=mpich
    ARMCI_STRIDED_METHOD=DIRECT
    ARMCI_IOV_METHOD=DIRECT
    ARMCI_NO_FLUSH_LOCAL=0
    ARMCI_RMA_ATOMICITY=0
  - MPI_IMPL=mpich
    ARMCI_STRIDED_METHOD=DIRECT
    ARMCI_IOV_METHOD=DIRECT
    ARMCI_NO_FLUSH_LOCAL=1
    ARMCI_RMA_ATOMICITY=0
  - MPI_IMPL=mpich
    ARMCI_STRIDED_METHOD=DIRECT
    ARMCI_IOV_METHOD=DIRECT
    ARMCI_NO_FLUSH_LOCAL=0
    ARMCI_RMA_ATOMICITY=1
  - MPI_IMPL=mpich
    ARMCI_STRIDED_METHOD=DIRECT
    ARMCI_IOV_METHOD=DIRECT
    ARMCI_NO_FLUSH_LOCAL=1
    ARMCI_RMA_ATOMICITY=1
# DIRECT+DIRECT rarely works
  - MPI_IMPL=openmpi
    ARMCI_STRIDED_METHOD=DIRECT
    ARMCI_IOV_METHOD=DIRECT
    ARMCI_NO_FLUSH_LOCAL=0
    ARMCI_RMA_ATOMICITY=0
  - MPI_IMPL=openmpi
    ARMCI_STRIDED_METHOD=DIRECT
    ARMCI_IOV_METHOD=DIRECT
    ARMCI_NO_FLUSH_LOCAL=1
    ARMCI_RMA_ATOMICITY=0
  - MPI_IMPL=openmpi
    ARMCI_STRIDED_METHOD=DIRECT
    ARMCI_IOV_METHOD=DIRECT
    ARMCI_NO_FLUSH_LOCAL=0
    ARMCI_RMA_ATOMICITY=1
  - MPI_IMPL=openmpi
    ARMCI_STRIDED_METHOD=DIRECT
    ARMCI_IOV_METHOD=DIRECT
    ARMCI_NO_FLUSH_LOCAL=1
    ARMCI_RMA_ATOMICITY=1
# without datatypes
  - MPI_IMPL=mpich
    ARMCI_STRIDED_METHOD=IOV
    ARMCI_IOV_METHOD=BATCHED
  - MPI_IMPL=openmpi
    ARMCI_STRIDED_METHOD=IOV
    ARMCI_IOV_METHOD=BATCHED
before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT
  - sh ./travis/install-autotools.sh $TRAVIS_ROOT
install:
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL
script:
  - sh ./travis/build-run.sh $TRAVIS_ROOT $MPI_IMPL
after_failure:
  - cat ./config.log
  - cat ./test-suite.log
  - find . -name "*.log" -exec head -n 100 {} ";"
